### ISSUE TITLE
Allow the use of iolists as parameters

### ISSUE THREAD

**Issue by hanikesn** [basho/riak-erlang-client#161]
update_type/*, fetch_type/* and modify_type/5 all allow the use of iolists as bucket name. (Despite type annotations). I found this quite useful for generating bucket names dynamically. This behaviour would also be useful for the riakc_obk functions. Even more so for the value parameters.

I propose to convert most binary parameters to also allow iolists to be passed.

**Comment by lukebakken** [comment]
@hanikesn - Please re-open this request if it is still applicable.

**Comment by Basho-JIRA** [comment]
Fixed, or closed via GitHub issues. 

***[posted via JIRA by Alexander Moore]***
