### ISSUE TITLE
Dialyzer complains when using {BucketType, Bucket} instead of just Bucket for gets [JIRA: CLIENTS-54]

### ISSUE THREAD

**Issue by ddrouin** [basho/riak-erlang-client#199]
When doing a get where the bucket type is specified (using the 2.0.0 version of the client):

riakc_pb_socket:get(Pid, {BinBucketType, BinBucket}, BinId)

Dialyzer complains:
The call riakc_pb_socket:get('undefined' | pid(),{binary(),binary()},BinId::binary()) will never return since the success typing is (pid(),binary(),binary()) -> 'unchanged' | {'error',_} | {'ok',{'riakc_obj','undefined' | binary() | {binary(),binary()},'undefined' | binary(),'undefined' | binary(),'undefined' | [{_,_}],'undefined' | dict(),'undefined' | binary()}} and the contract is (pid(),bucket(),key()) -> {'ok',riakc_obj()} | {'error',term()}

Looking in the riakc_pb_socket.erl module I see that the matching function has this spec:
-spec get(pid(), bucket(), key()) -> {ok, riakc_obj()} | {error, term()}.

and in riakc.hrl bucket() is defined as
-type bucket() :: binary(). %% A bucket name.

In the Erlang examples shown here though: http://docs.basho.com/riak/latest/dev/advanced/bucket-types/

It looks like a {binary(), binary()} is expected to be allowed:
{ok, Obj1} = riakc_pb_socket:get(Pid, {<<"default">>, <<"my_bucket">>},                              <<"my_key">>)

**Comment by khetzl** [comment]
Hi,
I provided a pull request #265 that fixes the issue by introducing a new type for the {BucketType, BucketName} tuple and adding it to the functions' typespec where it is expected by the code.

**Comment by Basho-JIRA** [comment]
https://github.com/basho/riak-erlang-client/issues/199 

***[posted via JIRA by Derek Somogyi]***
