### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by building39** [basho/riak-erlang-client#202]
I've added riak-erlang-client as a dependency in the rebar.config file of my e2 project:
  {riakc, ".*", {git, "git://github.com/basho/riak-erlang-client.git"}}

and get a version mismatch:

$ make
./rebar compile
==> e2 (compile)
==> modlib (compile)
==> riakc (compile)
Dependency not available: riak_pb-2.0.0.16 ({git,
                                             "git://github.com/basho/riak_pb",
                                             {tag,"2.0.0.16"}})
make: *** [compile] Error 1
mmartin@devcat:/data/git/nebula$ rm -rf deps/riak*
mmartin@devcat:/data/git/nebula$ make
./rebar compile
==> e2 (compile)
==> modlib (compile)
==> nebula (compile)
Dependency not available: riakc-.* ({git,
                                     "git://github.com/basho/riak-erlang-client.git"})
make: *** [compile] Error 1

**Comment by javajolt** [comment]
@building39 I just tried adding that dependency to a project and it worked fine. Can you try deleting your `deps` directory and try it again?  My line was seemingly the same as yours:
```
        {riakc, ".*", {git, "git://github.com/basho/riak-erlang-client.git"}},
```
Also, maybe try `make deps` (which runs `./rebar get-deps`) before `make`.

**Comment by building39** [comment]
Closing

**Comment by Basho-JIRA** [comment]
Fixed, or closed via GitHub issues. 

***[posted via JIRA by Alexander Moore]***
