### ISSUE TITLE
searching for "object:/" fails. [JIRA: CLIENTS-302]

### ISSUE THREAD

**Issue by building39** [basho/riak-erlang-client#209]
Using riak-erlang-client 2.1.0.1:
I have an object stored in riak, and one of the search fields contains simply "/". I can't retrieve this object using the erlang client, but I can get it by curling it out like so:

curl "$RIAK_HOST/search/query/my_idx?wt=json&q=objectName:\/"

The equivalent erlang:
riakc_pb_socket:search(Pid, <<"my_idx">>, <<"objectName:/">>).  -- or --
riakc_pb_socket:search(Pid, <<"my_idx">>, <<"objectName:\/">>).
returns:
{error,<<"Query unsuccessful check the logs.">>}

A little experimentation seems to indicate that any indexed field that starts with "/" cannot be found when using the erlang client (at least at 2.1.0.1). All queries work as expected using curl.

Am I doing something wrong?

**Comment by zeeshanlakhani** [comment]
we'll take a look at this next week @building39.

**Comment by zeeshanlakhani** [comment]
@building39 to escape a backslash, you'll need `\\`. 

Here's a test example I added that would get your search to work using the erlang client: https://github.com/basho/yokozuna/commit/df3430b4cd13cd9ec2fc6fb34c5640280c5fdba6#diff-5d0015658ff90b94cb1a00329ffafe00R211. 

Basically, ` <<"object_s:\\/*">>` for all values indexed with a prefix `/` for the object_s field :heavy_check_mark:

**Comment by Basho-JIRA** [comment]
Handled the "howto" in a test case that will be pushed into 2.Next. 

***[posted via JIRA by Zeeshan Lakhani]***
