### ISSUE TITLE
riak-erlang-client extension [JIRA: CLIENTS-531]

### ISSUE THREAD

**Issue by rhumbertgz** [basho/riak-erlang-client#222]
Hello,

I have been working in a extension to riak_pb, but every time that I try to use my new message in my extension of riak_erlang_client I obtain this message:

"Socket error while sending riakc request: einval. Bad value on output port 'tcp_inet'”. 

I put this question in the channel of riak at  https://webchat.freenode.net, but any answer. I also put replicate my error and put a post in GisHub with all the files:
https://gist.github.com/rhumbertgz/4881014e921572e7bca4 

Maybe I forgot to set some setting :(

Any suggestion?

Thanks in advance,
Humberto

**Comment by rhumbertgz** [comment]
Hello, I solved the problem with the help of <@Sargun> in the channel of riak at webchat.freenode.net.

The error was in the code of my message (625). This number (605 >= 255) breaks the format of 8-bit message code to identify the Protocol Buffers message.

I changed the code of my message and it works!

Thanks

**Comment by Basho-JIRA** [comment]
Fixed, or closed via GitHub issues. 

***[posted via JIRA by Alexander Moore]***
