### ISSUE TITLE
uniformly return {error, notfound} from single-key get to report the 'not found' case [JIRA: CLIENTS-772]

### ISSUE THREAD

**Issue by hmmr** [basho/riak-erlang-client#262]
Currently, for reasons lost in time, the single-key get (`riakc_ts:get`) returns an idiosyncratic `{ok, {[], []}}` if the key is not found. This issue is raised to change it to return `{error, notfound}` instead. The PR with a fix for riak-erlang-client is https://github.com/basho/riak-erlang-client/pull/263.

A newly written TS module for riak-erlang-http-client already has it: https://github.com/basho/riak-erlang-http-client/compare/riak_ts-develop...feature/az/http-client#diff-89ad4ccf2f97421d89d5f7e625001aabR115.

**Comment by Basho-JIRA** [comment]
We should be returning an empty set/list from the TS commands.  

***[posted via JIRA by Alexander Moore]***
