### ISSUE TITLE
updating, modifying map data type does not work for new instance [JIRA: CLIENTS-823]

### ISSUE THREAD

**Issue by kappac** [basho/riak-erlang-client#278]
I'm trying to create new map using `riakc_pd_socket:modify_type` or `riakc_pd_socket:update_type`.

In both cases client requeres context to create new map.

Creating a map as `riakc_map:new(riakc_map:new())` (the same way `modify_type` does) leads to `no function clause matching riak_dt_pb:encode(map, {map,[],[],[],undefined})`.

Is it a bug or am I doing something wrong?

Thanks in advance!

**Comment by kappac** [comment]
I'm sorry, this a problem in my code!

**Comment by Basho-JIRA** [comment]
Fixed, or closed via GitHub issues. 

***[posted via JIRA by Alexander Moore]***
