### ISSUE TITLE
Update map with disabled flag fail [JIRA: CLIENTS-824]

### ISSUE THREAD

**Issue by kappac** [basho/riak-erlang-client#279]
Hello

I'm trying to update map with riakc_flag disabled by default, and it leads to 'context_required' error.

There is an example in documentation shows flag could be disabled by default.

1> Map = riakc_map:new().
{map,[],[],[],undefined}

2> Map1 = riakc_map:update({<<"test">>, flag}, fun(F) -> riakc_flag:disable(F) end, Map).
** exception throw: context_required
     in function  riakc_flag:disable/1 (/home/kappac/Projects/Restaurant/data_access/_build/default/lib/riakc/src/riakc_flag.erl, line 102)
     in call from riakc_map:update/3 (/home/kappac/Projects/Restaurant/data_access/_build/default/lib/riakc/src/riakc_map.erl, line 163)

3> Map1 = riakc_map:update({<<"test">>, flag}, fun(F) -> riakc_flag:enable(F) end, Map).
{map,[],
     [{{<<"test">>,flag},{flag,false,enable,undefined}}],
     [],undefined}

rebar.config deps:
`{riakc, {git, "https://github.com/basho/riak-erlang-client.git", {branch, "master"}}},`

What is the right way to work with flags?

**Comment by kappac** [comment]
From riak channel at irc.freenode.net
> russelldb: the client is opinionated here, 'cos the api at riak allows that operation, but potentially unsafe

Would be great if this is discribed in documentation.
[Flags Within Maps](http://docs.basho.com/riak/kv/2.1.4/developing/data-types/#flags-within-maps)

**Comment by Basho-JIRA** [comment]
Fixed, or closed via GitHub issues. 

***[posted via JIRA by Alexander Moore]***
