### ISSUE TITLE
platform define for deprecated_now is limited to OTP 18 [JIRA: CLIENTS-857]

### ISSUE THREAD

**Issue by tsloughter** [basho/riak-erlang-client#284]
Because it is only set for 18 but is also required for all versions after 18 the build fails on 19: https://github.com/basho/riak-erlang-client/blob/master/rebar.config#L11

**Comment by lukebakken** [comment]
Going to use the regex from [this project](https://github.com/potatosalad/lftpc/blob/1.0.5/rebar.config#L4). Will test with several different erlangs.
