### ISSUE TITLE
incorrect response on put request when using autogenerated keys [JIRA: CLIENTS-873]

### ISSUE THREAD

**Issue by sata** [basho/riak-erlang-client#288]
Hi

I'm running a Riak 2.0.6-1 cluster with riak erlang client lib version 2.1.1, riak_pb 2.1.0.2.

According to the README.md

> If the return value of the last command was anything but the atom ok (or {ok, Key} when you instruct the server to generate the key), then the store failed.

Which is expressed in the code[1] as well. This is the same function header as in 2.1.1.

While the response I get is:

> {ok,{riakc_obj,{<<"bucket_type">>,<<"bucket">>},
>                <<"DYih3nkXtFi6ytGm7T2q7pjG2DG">>,undefined,[],undefined,
>                undefined}}
> 

The object itself is created with undefined as key:
`              Obj = riakc_obj:new(?REQUEST_BUCKET, undefined, to_binary(Req)),`

When I traced the process_response/3 function I saw this, I'll only include the interesting bits:
```
(<0.231.0>) call riakc_pb_socket:process_response(
                   {request,#Ref<0.0.2.19281>,
                      {rpbputreq, ... },
                   {rpbputresp,[],undefined,<<"1lZ4hsH4Y6RB5aYtkVj8JTqNCAh">>},
                   {state, ...}
                  )
```

rpbputresp is defined as:
```
-record(rpbputresp, {
    content = [],
    vclock,
    key
}).
```

If we review the call, we see that content is set to [], while in [1] it's expected to be undefined thus the pattern match doesn't work.

I changed the code to pattern match against content [] and I did receive {ok, <<"key">>}. 

In [2] for #rpbgetresp empty list is being pattern matched not undefined.

I can create a PR if this is what you guys think is correct fix. 

Cheers,

[1] https://github.com/basho/riak-erlang-client/blob/eed70717ece9c6796e29b5a326fa6af98b2ec43a/src/riakc_pb_socket.erl#L1661-L1666
[2] https://github.com/basho/riak-erlang-client/blob/eed70717ece9c6796e29b5a326fa6af98b2ec43a/src/riakc_pb_socket.erl#L1644-L1645

**Comment by sata** [comment]
Managed to create a duplicate ticket during GitHub 'minor' issues.

**Comment by Basho-JIRA** [comment]
Fixed, or closed via GitHub issues. 

***[posted via JIRA by Alexander Moore]***
