### ISSUE TITLE
riakc_pb_socket:list_buckets documentation should refer to bucket types [JIRA: CLIENTS-885]

### ISSUE THREAD

**Issue by bashoshaun** [basho/riak-erlang-client#292]
The @edoc for `riakc_pb_socket:list_buckets/1` currently reads `List all buckets on the server.`  It should be slightly expanded to read `List all buckets on the server under the default bucket type.`

Going further, the @edocs for all of the `list_buckets()` definitions should include the usage of bucket types.  As things stand, it looks like all the edocs for this function was written before bucket types were introduced and wasn't updated when the concept was later added to Riak.

**Comment by lukebakken** [comment]
A PR for these changes would be very welcome.
