### ISSUE TITLE
Function counter_incr is broken [JIRA: CLIENTS-886]

### ISSUE THREAD

**Issue by greggy** [basho/riak-erlang-client#293]
I'm trying to use CRDT counters and get such error:

`(maindev1@127.0.0.1)18> Pid = poolboy:checkout(riak_pool).`
`<0.7549.0>`

`(maindev1@127.0.0.1)19> riakc_pb_socket:get_bucket_type(Pid, <<"counters">>).`
`{ok,[{n_val,3},`
 `    ...`
`     {allow_mult,true},`
`     ...`
 `    {datatype,counter}]}`
`(maindev1@127.0.0.1)20> riakc_pb_socket:counter_incr(Pid, <<"counters">>, <<"referrer_payments">>, 1).`
`{error,<<"\"Counters require bucket property 'allow_mult=true'\"">>}`

What it can be?

**Comment by lukebakken** [comment]
Could you please use the `riak-admin` command to list your bucket types and print the status of the `counters` type? Something like this:

```
$ riak-admin bucket-type list
default (active)
search_type (active)
set_bucket (active)
counter_bucket (active)
yokozuna (active)
sets (active)
write_once (active)
map_bucket (active)
maps (active)
other_counters (active)
counters (active)
mr (active)
plain (active)
no_siblings (active)

$ riak-admin bucket-type status counter_bucket
counter_bucket is active

young_vclock: 20
w: quorum
small_vclock: 50
rw: quorum
r: quorum
pw: 0
precommit: []
pr: 0
postcommit: []
old_vclock: 86400
notfound_ok: true
n_val: 3
linkfun: {modfun,riak_kv_wm_link_walker,mapreduce_linkfun}
last_write_wins: false
dw: quorum
dvv_enabled: true
chash_keyfun: {riak_core_util,chash_std_keyfun}
big_vclock: 50
basic_quorum: false
allow_mult: true
datatype: counter
active: true
claimant: 'dev1@127.0.0.1'
```

**Comment by lukebakken** [comment]
`counter_incr` is a function that modifies an "old style" Riak counter. Your bucket type is set up to use the new CRDT counter which means you should be using the [functions listed here](https://github.com/basho/riak-erlang-client#counters).

I'll close this issue now but please re-open it if you run into further issues.
