### ISSUE TITLE
Search + MapReduce Using PB Client [JIRA: CLIENTS-1026]

### ISSUE THREAD

**Issue by mikrofusion** [basho/riak-erlang-client#329]
The documentation appears to only show how to pipe search results to MapReduce using HTTP:  https://docs.basho.com/riak/kv/2.1.4/developing/usage/search/#mapreduce

After a bit of investigation, we have been unable to figure out how to do the equivalent thing using this client.  The ability to pipe search results to map_reduce is important to us as it could help avoid multiple trips from our servers to Riak.

Thanks in advance for any info you can provide to send us in the right direction on this.

**Comment by lukebakken** [comment]
I believe my comment on #330 applies here. Retrieving objects in parallel by their key is always faster than using MapReduce (which I believe is what you'd like to accomplish here).

Solr allows storing additional data that can be returned in search results. You would create a [custom schema](http://docs.basho.com/riak/kv/2.1.4/developing/usage/search-schemas/) where certain fields are not indexed (`indexed="false"`) but they *are* stored (`stored="true"`). Then, when you execute your search, you get this data as well and will not require additional fetches.

**Comment by Basho-JIRA** [comment]
Fixed, or closed via GitHub issues. 

***[posted via JIRA by Alexander Moore]***
