### ISSUE TITLE
non-Semantic Versioning format

### ISSUE THREAD

**Issue by the-prksh** [basho/riak-erlang-client#400]
Hello,

Due to non-Semantic Versioning format (like `riak_kv-3.0.2`) `mix` is not able to pull.

```elixir
===> Compiling riakc
Unchecked dependencies for environment dev:
* riak_pb (https://github.com/basho/riak_pb - riak_kv-3.0.2)
  the app file specified a non-Semantic Versioning format: "riak_kv-3.0.2". Mix can only match the requirement ">= 0.0.0" against semantic versions. Please fix the application version or use a regular expression as a requirement to match against any version
** (Mix) Can't continue due to errors on dependencies
```

Can't we have Semantic Versioning ? 

/prakash

**Comment by martinsumner** [comment]
I've been trying to remember why we went in the other direction.  I don't think at the time there was consideration given to things like mix just not working without semantic versioning.

So, standardising on semantic versioning (again) is probably the right thing to do.

There is a release pending to fix a bug, and as part of this I'm having to address travis being broken (no longer free for OSS), so my intention is to address versioning as well as part of this.

**Comment by martinsumner** [comment]
Sorry for the delay with this.  Just been puzzling over how to handle versioning of cloned repos (e.g. https://github.com/basho/rebar3_gpb_plugin).

I would prefer not to overlap and conflict with the source repo versioning.  The intention is to use `<build>` references

e.g. 2.15.1+riak.3.0.4

**Comment by martinsumner** [comment]
Both erlang clients now have semantic version support:

https://github.com/basho/riak-erlang-client/releases/tag/3.0.4
https://github.com/basho/riak-erlang-http-client/releases/tag/3.0.4
