### ISSUE TITLE
deprecated_19 is not defined for OTP24

### ISSUE THREAD

**Issue by javobalazs** [basho/riak-erlang-client#408]
`rebar.config` in the latest branch only has this at line no. 7:

```erlang
{erl_opts, [
    debug_info,
    warnings_as_errors,
    {platform_define, "^[0-9]+", namespaced_types},
    {platform_define, "(?=^[0-9]+)(?!^17)", deprecated_now},
    {platform_define, "^19", deprecated_19},
    {platform_define, "^20", deprecated_19},
    {platform_define, "^21", deprecated_19},
    {platform_define, "^22", deprecated_19},
    {platform_define, "^23", deprecated_19}
]}.
```

OTP24 is now widely used, and we have actually had a problem with this, in `src/riak_pb_socket.erl` line no. 3369.
I suggest `deprecated_19` be defined as the default.

**Comment by martinsumner** [comment]
[The branch `develop-3.2-otp24`](https://github.com/basho/riak-erlang-client/blob/develop-3.2-otp24/rebar.config) is where higher OTP versions are supported, this is what we're testing for the Riak 3.2.0 release (which supports OTP 22/24/25) - but it should work against the Riak 3.0 releases.

There should be a release based on this branch soon, but for now see if it resolves your issues.
