### ISSUE TITLE
update value from encode type "application/x-erlang-binary" to binary

### ISSUE THREAD

**Issue by garyhai** [basho/riak-erlang-client#60]
When update value from encode type "application/x-erlang-binary", eg. integer  to binary, may cause decode error because of the encode type is not update to 'undefined' as update to other encode type eg. string "hello".

Code sample:

    riak_put(Pid, Bucket, Key, Value, Options, Timeout) ->
      case riakc_pb_socket:get(Pid, Bucket, Key, [head | Options], Timeout) of
        {ok, Obj} when is_binary(Value) ->  % @notice fix bug of riakc
          %% replace old content-type to null ""
           NewObj = riakc_obj:update_value(Obj, Value, ""),
           riakc_pb_socket:put(Pid, NewObj, Options, Timeout);
        {ok, Obj} ->
          NewObj = riakc_obj:update_value(Obj, Value),
          riakc_pb_socket:put(Pid, NewObj, Options, Timeout);
        Error ->
          Error
      end.

**Comment by lukebakken** [comment]
If a more comprehensive example can be given that would be great. Otherwise, I don't understand the issue as presented.
